version: 2.0
jobs:
  build:
    docker:
       - image: alantrrs/cuda-opencv:latest
#      - image: nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
    working_directory: ~/work
    steps:
      - checkout
      - run: mkdir dist
      - run: make LIBSO=1 GPU=0 CUDNN=0 OPENCV=0 -j 8
      - run: zip -9 -r ~/work/dist/darknet-libso.zip ~/work -x ~/work/obj/**\* ~/work/.git/**\*
      - store_artifacts:
         path: ~/work/dist/darknet-libso.zip
      - run: make clean
      - run: make LIBSO=1 GPU=0 CUDNN=0 OPENCV=1 -j 8
      - run: zip -9 -r ~/work/dist/darknet-libso-opencv.zip ~/work -x ~/work/obj/**\* ~/work/.git/**\*
      - store_artifacts:
         path: ~/work/dist/darknet-libso-opencv.zip
      - run: make clean
      - run: make LIBSO=1 GPU=1 CUDNN=1 OPENCV=1 -j
      - run: zip -9 -r ~/work/dist/darknet-libso-gpu-cudnn-opencv.zip ~/work -x ~/work/obj/**\* ~/work/.git/**\*
      - store_artifacts:
         path: ~/work/dist/darknet-libso-gpu-cudnn-opencv.zip
      - run: make clean
      - run: make LIBSO=1 GPU=1 CUDNN=1 OPENCV=1 CUDNN_HALF=1 -j 8
      - run: zip -9 -r ~/work/dist/darknet-libso-gpu-cudnn-opencv-cudnn-half.zip ~/work -x ~/work/obj/**\* ~/work/.git/**\*
      - store_artifacts:
         path: ~/work/dist/darknet-libso-gpu-cudnn-opencv-cudnn-half.zip
         
